name: Windows package build
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, windows, X64, opam-2-3]
    steps:
      - name: Check out repo        
        uses: actions/checkout@v4
      - name: Build EverParse
        shell: C:\cygwin64\bin\bash.exe --login '{0}'
        run: |
          eval $(opam env) && CC=x86_64-w64-mingw32-gcc.exe make -C $GITHUB_WORKSPACE -j 8 everparse && echo "There is a CR at the end of this line"
      - name: Archive EverParse package
        uses: actions/upload-artifact@v4
        with:
          name: everparse
          path: everparse
          include-hidden-files: true
  test:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download and extract artifact
        uses: actions/download-artifact@v4
        with:
          name: everparse
      - name: Test EverParse
        shell: cmd
        run: |
          .\everparse\everparse.cmd src\3d\tests\Arithmetic.3d src\3d\tests\FieldDependence0.3d && .\everparse\everparse.cmd src\3d\tests\Comments.3d && .\everparse\everparse.cmd --check_hashes inplace src\3d\tests\Comments.3d
